// Generated by https://quicktype.io

export interface NewsResponse {
  status:       string;
  totalResults: number;
  articles:     Article[];
}

export interface Article {
  source:      Source;
  author:      Author;
  title:       string;
  description: string;
  url:         string;
  urlToImage:  string;
  publishedAt: string;
  content:     string;
}

export enum Author {
  BBCNews = "BBC News",
  BBCSport = "BBC Sport",
}

export interface Source {
  id:   ID;
  name: Author;
}

export enum ID {
  BbcNews = "bbc-news",
}
